.so Tmac.mm-etc
.if t .Newcentury-fonts
.INITR* \n[.F]
.GETST* SCORE-TOTAL-END SCORE-TOTAL-END
.TITLE CMPS-109 "Advanced Programming" Spring\~2014 Test\~#1
.RCS "$Id: cmps109-2014q2-exam1.mm,v 1.29 2014-04-22 18:00:41-07 - - $"
.DS
.PS
examboxes(3)
.PE
.DE
.P
.ft BI
No books\(;;
No calculator\(;;
No computer\(;;
No email\(;;
No internet\(;;
No notes\(;;
No phone.
Neatness counts\(!!
Do your scratch work elsewhere and enter only your final
answer into the spaces provided.
.ft R
.EQ
delim $$
.EN
.de LIQ
.   LI
..
.ALX 1
.LI
Implicitly generated members for class
.V= foo .
.ALX a () "" 0
.LI
Write the prototypes of the class members implicitly generated
by a C++98 compiler.
.SCORE-HERE 2
.SP .8i
.LI
Write the prototypes implicitly generated by a C++11 compiler that
were not part of C++98.
.SCORE-HERE 1
.SP .6i
.LE
.LI
Given the declaration
.V= "map<string,string>\~m;"
write a loop that explicitly uses iterators to print each 
key and value pair, one pair per line.
.SCORE-HERE 2
.SP 1.2i
.LI
Given the declaration
.V= "map<string,string>\~m;"
write a loop that writes out each key and value pair,
one pair per line,
but do not code anything that explicitly uses an iterator.
Hint\(::
use a C++11 feature not present in C++98.
.SCORE-HERE 2
.SP 1.2i
.LI
Write a function which will reverse a container.
Assume it has bidirectional iterators produced by
.V= begin()
and
.V= end() .
For example,
{1,2,3,4,5}
should become
{5,4,3,2,1}.
You may use
.VTCODE* 1 "template <typename T> void std::swap (T&, T&);"
from the standard library.
.SCORE-HERE 3
.DS
.ft CB
template <typename container>
void reverse (container& con) {
.DE
.SP 10i
.LI
Write a function split which takes an input container
and copies alternate elements into two output containers.
For example, if the input container has {1,2,3,4,5,6,7,8,9}
then the first output container is assigned {1,3,5,7,9}
and the second output container is assigned {2,4,6,8}.
Assume forward iterators and the function
.V= push_back .
.SCORE-HERE 3
.DS
.ft CB
template <typename T>
void split (const T& input, T& first, T&second) {
.DE
.SP 1.2i
.LI
Define
.V= operator=
as it would appear in a 
.V= \&.cpp
file for the class 
.V= quux .
A partial header is shown here.
.SCORE-HERE 3
.DS
.ft CB
class quux {
   private:
      int i;
      string s;
      vector<int>* vip;
      counter* ct;
   public:
      quux& operator= (const quux&);
};
.DE
.SP .5i
.LI
Finish the definition of class
.V= stack .
Since the stack is implemented as containing a vector,
the implicitly provided members all work and need not be defined.
Define the following public members as 
.E= inline
functions which operate on the vector\(::
.V= push ,
.V= pop ,
.V= top ,
.V= size ,
.V= empty ,
.V= begin ,
.V= end .
Iteration on the stack should begin at the top and end at the bottom.
.SCORE-HERE 4
.DS
.ft CB
template <typename T>
class stack {
   private:
      vector<T> data;
      typedef typename vector<value_type>::const_reverse_iterator
              const_iterator;
   public:
.DE
.LE
.SP 10i
.if t .2C
.\".nr Ds 0
Multiple choice.
To the
.E= left
of each question,
write the letter that indicates your answer.
Write
.E= Z
if you don't want to risk a wrong answer,
which count negative points.
.nr MULTCHOICE_MAX 12
.SCORE-HERE \n[MULTCHOICE_MAX]
.P
.DS
.TS
tab(|); |l2 |r2w(32p) |l0 r2 |r0w(32p) l |.
_
number of||×|1 =||$= a$
correct answers
_
number of||×|\[12] =||$= b$
wrong answers
_
number of|\0\0\0|×|0 =|0
missing answers
_
column total|\n[MULTCHOICE_MAX]||||$= c$
$ c = max ( a - b , 0 ) $
_
.TE
.DE
.ALX 1
.CHOOSE-BEGIN
In the absense of specific reasons against it,
what should the default container be\(??
.CHOOSE4V deque list string vector
.CHOOSE-END
.CHOOSE-BEGIN
What class replaces pointers and does memory management by
reference counting\(??
.CHOOSE4V auto_ptr reference_ptr shared_ptr unique_ptr
.CHOOSE-END
.CHOOSE-BEGIN
If
.V= operator<<
is declared as a friend of class
.V= foo ,
what should be its signature\(??
.CHOOSE
.V= "ostream& operator<< ("
.br
.V= "\0\0\0\0const ostream&, const foo&);"
.CHOOSE
.V= "ostream& operator<< ("
.br
.V= "\0\0\0\0const ostream&, foo&);"
.CHOOSE
.V= "ostream& operator<< ("
.br
.V= "\0\0\0\0ostream&, const foo&);"
.CHOOSE
.V= "ostream& operator<< ("
.br
.V= "\0\0\0\0ostream&, foo&);"
.CHOOSE-END
.CHOOSE-BEGIN
Given the declarations
.VTCODE* 1 "string s; string t;"
which is impossible\(??
.CHOOSE4V "s != t and &s != &t" "s != t and &s == &t" \
"s == t and &s != &t" "s == t and &s == &t"
.CHOOSE-END
.CHOOSE-BEGIN
The default copy and move constructors are inappropriate
if a class object contains what kind of data member\(??
.CHOOSE4 pointer primitive string vector
.CHOOSE-END
.CHOOSE-BEGIN
Given the declaration
.V= foo\~x; ,
what is the correct prototype for
.V= update
so that it may change the contents of
.V= x
if called as
.V= update(x) \(??
.CHOOSE4V "void update (foo&&);" "void update (foo&);" \
"void update (foo);" "void update (foo*);"
.CHOOSE-END
.CHOOSE-BEGIN
If a function member refers to a data member
.V= x
without qualification,
it is equivalent to what expression\(??
.CHOOSE4V auto->x self->x that->x this->x
.CHOOSE-END
.CHOOSE-BEGIN
What is the declaration of the postfix
.V= operator--
which is a member of class
.V= foo \(??
.CHOOSE4V "foo &operator-- ();" "foo &operator-- (foo &);" \
"foo operator-- (foo &, int);" "foo operator-- (int);" 
.CHOOSE-END
.CHOOSE-BEGIN
Using
.V= new
but never using
.V= delete
results in\(::
.CHOOSE4 dangling\~pointer memory\~leak null\~pointer \
segmentation\~fault
.CHOOSE-END
.CHOOSE-BEGIN
If
.V= v.size()\~==\~10 ,
then
.V= v.end()
is equivalent to the address of\(::
.CHOOSE4V v[-1] v[0] v[9] v[10]
.CHOOSE-END
.CHOOSE-BEGIN
Searching for a particular item in which of these containers
will have a running time of $ O ( log sub 2 n ) $\(??
.CHOOSE4V list map unordered_map vector
.CHOOSE-END
.CHOOSE-BEGIN
Which is the proper way to catch an exception called
.V= exn \(??
.CHOOSE4V "catch (exn &&e)" "catch (exn &e)" "catch (exn *e)" \
"catch (exn e)"
.CHOOSE-END
.LE
.FINISH
