# Makefile.dep created Sun Apr 26 17:41:25 PDT 2015
bigint.o: bigint.cpp bigint.h util.h debug.h
scanner.o: scanner.cpp scanner.h debug.h
debug.o: debug.cpp debug.h util.h
util.o: util.cpp util.h debug.h
main.o: main.cpp bigint.h util.h debug.h iterstack.h scanner.h
