# Makefile.dep created Tue May 26 23:57:23 PDT 2015
debug.o: debug.cpp debug.h util.h util.tcc
graphics.o: graphics.cpp graphics.h rgbcolor.h shape.h util.h debug.h \
 util.tcc
interp.o: interp.cpp debug.h interp.h graphics.h rgbcolor.h shape.h \
 util.h util.tcc
rgbcolor.o: rgbcolor.cpp rgbcolor.h colors.cppgen
shape.o: shape.cpp shape.h rgbcolor.h util.h debug.h util.tcc
util.o: util.cpp util.h debug.h util.tcc
main.o: main.cpp debug.h graphics.h rgbcolor.h shape.h interp.h util.h \
 util.tcc
